import dotenv from 'dotenv';
dotenv.config();

import { getSequelize } from './src/config/sequelize.js';

/**
 * run-seeders.js
 *
 * Idempotent seed script — skips records that already exist (catches duplicate errors).
 * Safe to run multiple times.
 *
 * For a FULL reseed (wipe + reinsert), use: node reseed-db.js
 *
 * Seed data mirrors reseed-db.js:
 *   - 2 users
 *   - 30 gemstones (all 12 zodiacs, all 8 purposes, unique images)
 *   - 2 sample recommendations
 *
 * PREREQUISITE: Migration 0004 must be run first (extends category ENUM with
 * 'success' and 'health'). Run node setup-db.js before this script.
 */

const GEMSTONES = [
  {
    id: 1,
    name: 'Rose Quartz',
    description: 'A gentle stone of unconditional love and infinite peace. It opens the heart to all forms of love and promotes deep inner healing.',
    zodiacSigns: JSON.stringify(['Taurus', 'Libra', 'Pisces']),
    birthMonths: JSON.stringify([2, 6, 10]),
    category: 'love',
    color: 'Rose Pink',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=300&fit=crop',
    price: 1499.00,
    currency: 'INR',
    stock: 25,
    buyLink: 'https://www.amazon.in/s?k=rose+quartz+gemstone',
    benefits: 'love|healing|emotional healing|peace|relationships|comfort|compassion',
    inStock: true,
  },
  {
    id: 2,
    name: 'Amethyst',
    description: 'A powerful protective stone that enhances clarity of mind, promotes sobriety, and calms the nervous system for focused awareness.',
    zodiacSigns: JSON.stringify(['Aries', 'Capricorn', 'Pisces']),
    birthMonths: JSON.stringify([1, 2, 11]),
    category: 'clarity',
    color: 'Purple',
    imageUrl: 'https://images.unsplash.com/photo-1524234107702-53ec2a9e5e2c?w=400&h=300&fit=crop',
    price: 2399.00,
    currency: 'INR',
    stock: 15,
    buyLink: 'https://www.amazon.in/s?k=amethyst+gemstone',
    benefits: 'clarity|focus|peace|protection|healing|health|spirituality|mindfulness',
    inStock: true,
  },
  {
    id: 3,
    name: 'Citrine',
    description: 'The stone of abundance and energy. Citrine energises every level of life and attracts wealth, prosperity, and success.',
    zodiacSigns: JSON.stringify(['Leo', 'Virgo', 'Gemini']),
    birthMonths: JSON.stringify([6, 7, 8]),
    category: 'energy',
    color: 'Golden Yellow',
    imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=300&fit=crop',
    price: 3499.00,
    currency: 'INR',
    stock: 12,
    buyLink: 'https://www.amazon.in/s?k=citrine+gemstone',
    benefits: 'wealth|energy|optimism|prosperity|success|abundance|joy|vitality',
    inStock: true,
  },
  {
    id: 4,
    name: 'Black Obsidian',
    description: 'A strongly protective volcanic glass that forms a shield against negativity, absorbs mental stress, and anchors the spirit.',
    zodiacSigns: JSON.stringify(['Scorpio', 'Aries', 'Capricorn']),
    birthMonths: JSON.stringify([10, 11, 12]),
    category: 'protection',
    color: 'Dark Black',
    imageUrl: 'https://images.unsplash.com/photo-1599643478859-e61611cbbf3d?w=400&h=300&fit=crop',
    price: 999.00,
    currency: 'INR',
    stock: 30,
    buyLink: 'https://www.amazon.in/s?k=obsidian+gemstone',
    benefits: 'protection|grounding|safety|healing|health|ward off negativity|clarity',
    inStock: true,
  },
  {
    id: 5,
    name: 'Tiger Eye',
    description: 'A stone of courage, confidence, and prosperity. Tiger Eye brings clarity of intention and sharpens focus for wealth creation.',
    zodiacSigns: JSON.stringify(['Leo', 'Capricorn', 'Gemini']),
    birthMonths: JSON.stringify([5, 8, 11]),
    category: 'wealth',
    color: 'Honey Brown',
    imageUrl: 'https://images.unsplash.com/photo-1622159637383-b3ae82bfdb94?w=400&h=300&fit=crop',
    price: 1799.00,
    currency: 'INR',
    stock: 18,
    buyLink: 'https://www.amazon.in/s?k=tiger+eye+gemstone',
    benefits: 'wealth|confidence|focus|success|courage|prosperity|energy',
    inStock: true,
  },
  {
    id: 6,
    name: 'Jade',
    description: 'The dream stone of ancient wisdom. Jade attracts good luck and friendship while stabilising the personality and promoting harmony.',
    zodiacSigns: JSON.stringify(['Cancer', 'Libra', 'Taurus']),
    birthMonths: JSON.stringify([6, 7]),
    category: 'healing',
    color: 'Imperial Green',
    imageUrl: 'https://images.unsplash.com/photo-1627912947853-c9b0aed4e9af?w=400&h=300&fit=crop',
    price: 2999.00,
    currency: 'INR',
    stock: 8,
    buyLink: 'https://www.amazon.in/s?k=jade+gemstone',
    benefits: 'healing|health|balance|wealth|prosperity|harmony|luck',
    inStock: true,
  },
  {
    id: 7,
    name: 'Lapis Lazuli',
    description: 'A royal stone of wisdom and truth. Lapis Lazuli stimulates enlightenment, enhances dream work, and encourages self-awareness.',
    zodiacSigns: JSON.stringify(['Sagittarius', 'Aquarius', 'Virgo']),
    birthMonths: JSON.stringify([9, 11, 12]),
    category: 'clarity',
    color: 'Deep Blue',
    imageUrl: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=400&h=300&fit=crop',
    price: 4199.00,
    currency: 'INR',
    stock: 10,
    buyLink: 'https://www.amazon.in/s?k=lapis+lazuli+gemstone',
    benefits: 'clarity|wisdom|truth|focus|spirituality|peace|mindfulness|success',
    inStock: true,
  },
  {
    id: 8,
    name: 'Moonstone',
    description: 'A stone of new beginnings and inner growth. Moonstone soothes emotional instability and promotes intuition and empathy.',
    zodiacSigns: JSON.stringify(['Cancer', 'Scorpio', 'Pisces']),
    birthMonths: JSON.stringify([6, 7, 9]),
    category: 'love',
    color: 'Pearlescent White',
    imageUrl: 'https://images.unsplash.com/photo-1573408301185-9521c040f8d0?w=400&h=300&fit=crop',
    price: 3299.00,
    currency: 'INR',
    stock: 14,
    buyLink: 'https://www.amazon.in/s?k=moonstone+gemstone',
    benefits: 'love|healing|emotional healing|peace|relationships|intuition|comfort',
    inStock: true,
  },
  {
    id: 9,
    name: 'Pyrite',
    description: 'Fools Gold that brings real fortune. Pyrite is a powerful protective and wealth-attracting stone that stimulates confidence.',
    zodiacSigns: JSON.stringify(['Aries', 'Leo', 'Scorpio']),
    birthMonths: JSON.stringify([3, 8, 10]),
    category: 'wealth',
    color: 'Metallic Gold',
    imageUrl: 'https://images.unsplash.com/photo-1519785701017-f36c3d53d4aa?w=400&h=300&fit=crop',
    price: 1299.00,
    currency: 'INR',
    stock: 22,
    buyLink: 'https://www.amazon.in/s?k=pyrite+crystal+gemstone',
    benefits: 'wealth|prosperity|abundance|confidence|success|courage|energy',
    inStock: true,
  },
  {
    id: 10,
    name: 'Black Tourmaline',
    description: 'The most powerful of all protective crystals. Black Tourmaline repels and blocks negative energies and psychic attack.',
    zodiacSigns: JSON.stringify(['Capricorn', 'Scorpio', 'Libra']),
    birthMonths: JSON.stringify([1, 10, 11]),
    category: 'protection',
    color: 'Jet Black',
    imageUrl: 'https://images.unsplash.com/photo-1601821765780-754fa98637c1?w=400&h=300&fit=crop',
    price: 1599.00,
    currency: 'INR',
    stock: 20,
    buyLink: 'https://www.amazon.in/s?k=black+tourmaline+crystal',
    benefits: 'protection|grounding|safety|ward off negativity|healing|health|clarity',
    inStock: true,
  },
  {
    id: 11,
    name: 'Carnelian',
    description: 'A stabilising stone that restores vitality and motivation. Carnelian stimulates creativity, courage, and positive life choices.',
    zodiacSigns: JSON.stringify(['Aries', 'Leo', 'Cancer']),
    birthMonths: JSON.stringify([3, 7, 8]),
    category: 'energy',
    color: 'Sunset Orange',
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e2a7ca78cfc0?w=400&h=300&fit=crop',
    price: 899.00,
    currency: 'INR',
    stock: 28,
    buyLink: 'https://www.amazon.in/s?k=carnelian+gemstone',
    benefits: 'energy|vitality|creativity|courage|success|joy|optimism|confidence',
    inStock: true,
  },
  {
    id: 12,
    name: 'Green Aventurine',
    description: 'The stone of opportunity. Green Aventurine is one of the luckiest crystals, bringing prosperity, success, and career advancement.',
    zodiacSigns: JSON.stringify(['Aries', 'Taurus', 'Virgo']),
    birthMonths: JSON.stringify([3, 4, 5]),
    category: 'success',
    color: 'Forest Green',
    imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0729?w=400&h=300&fit=crop',
    price: 1099.00,
    currency: 'INR',
    stock: 35,
    buyLink: 'https://www.amazon.in/s?k=green+aventurine+gemstone',
    benefits: 'success|luck|prosperity|wealth|abundance|confidence|ambition|courage',
    inStock: true,
  },
  {
    id: 13,
    name: 'Blue Sapphire',
    description: 'The wisdom stone of focus and discipline. Blue Sapphire brings order and clarity, attracts prosperity, and fulfils dreams.',
    zodiacSigns: JSON.stringify(['Taurus', 'Virgo', 'Capricorn']),
    birthMonths: JSON.stringify([4, 9, 12]),
    category: 'success',
    color: 'Royal Blue',
    imageUrl: 'https://images.unsplash.com/photo-1548586196-aa5803b77379?w=400&h=300&fit=crop',
    price: 8999.00,
    currency: 'INR',
    stock: 5,
    buyLink: 'https://www.amazon.in/s?k=blue+sapphire+gemstone',
    benefits: 'success|clarity|focus|wisdom|prosperity|wealth|ambition|confidence',
    inStock: true,
  },
  {
    id: 14,
    name: 'Garnet',
    description: 'A stone of health and vitality that regenerates the body and stimulates the metabolism. Garnet revitalises, purifies, and balances energy.',
    zodiacSigns: JSON.stringify(['Capricorn', 'Aquarius', 'Leo']),
    birthMonths: JSON.stringify([1, 2, 7]),
    category: 'health',
    color: 'Deep Crimson',
    imageUrl: 'https://images.unsplash.com/photo-1587049633312-d628ae50a8ae?w=400&h=300&fit=crop',
    price: 2199.00,
    currency: 'INR',
    stock: 16,
    buyLink: 'https://www.amazon.in/s?k=garnet+gemstone',
    benefits: 'health|healing|vitality|energy|love|relationships|protection|grounding',
    inStock: true,
  },
  {
    id: 15,
    name: 'Aquamarine',
    description: 'The courage stone of clarity and calm. Aquamarine reduces stress, quiets the mind, and helps filter out unnecessary information.',
    zodiacSigns: JSON.stringify(['Pisces', 'Gemini', 'Aquarius']),
    birthMonths: JSON.stringify([2, 3, 8]),
    category: 'clarity',
    color: 'Ocean Blue',
    imageUrl: 'https://images.unsplash.com/photo-1560343787-f4c9da9c0416?w=400&h=300&fit=crop',
    price: 4999.00,
    currency: 'INR',
    stock: 9,
    buyLink: 'https://www.amazon.in/s?k=aquamarine+gemstone',
    benefits: 'clarity|peace|courage|healing|health|focus|spirituality|mindfulness',
    inStock: true,
  },
  {
    id: 16,
    name: 'Labradorite',
    description: 'A stone of transformation and magic. Labradorite is a highly mystical and protective stone that raises consciousness.',
    zodiacSigns: JSON.stringify(['Leo', 'Scorpio', 'Sagittarius']),
    birthMonths: JSON.stringify([8, 10, 11]),
    category: 'protection',
    color: 'Iridescent Grey-Blue',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=300&fit=crop',
    price: 2799.00,
    currency: 'INR',
    stock: 11,
    buyLink: 'https://www.amazon.in/s?k=labradorite+crystal',
    benefits: 'protection|grounding|ward off negativity|clarity|spirituality|energy|success',
    inStock: true,
  },
  {
    id: 17,
    name: 'Turquoise',
    description: 'An ancient healing stone that brings together heaven and earth. Turquoise enhances communication, promotes empathy and positive thinking.',
    zodiacSigns: JSON.stringify(['Sagittarius', 'Pisces', 'Gemini']),
    birthMonths: JSON.stringify([5, 11, 12]),
    category: 'healing',
    color: 'Sky Turquoise',
    imageUrl: 'https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=400&h=300&fit=crop',
    price: 3199.00,
    currency: 'INR',
    stock: 13,
    buyLink: 'https://www.amazon.in/s?k=turquoise+gemstone',
    benefits: 'healing|health|peace|clarity|protection|luck|communication|balance',
    inStock: true,
  },
  {
    id: 18,
    name: 'Ruby',
    description: 'The stone of passion, vitality, and divine love. Ruby promotes dynamic leadership, encourages passion, and brings prosperity.',
    zodiacSigns: JSON.stringify(['Leo', 'Cancer', 'Scorpio']),
    birthMonths: JSON.stringify([7, 8]),
    category: 'energy',
    color: 'Pigeon Blood Red',
    imageUrl: 'https://images.unsplash.com/photo-1515449979595-6f4e27e4e7a4?w=400&h=300&fit=crop',
    price: 12999.00,
    currency: 'INR',
    stock: 4,
    buyLink: 'https://www.amazon.in/s?k=ruby+gemstone',
    benefits: 'energy|vitality|love|passion|wealth|success|courage|confidence',
    inStock: true,
  },
  {
    id: 19,
    name: 'Emerald',
    description: 'The stone of successful love. Emerald opens the heart chakra, bestows loyalty, enhances unconditional love, and promotes friendship.',
    zodiacSigns: JSON.stringify(['Cancer', 'Taurus', 'Gemini']),
    birthMonths: JSON.stringify([4, 5, 6]),
    category: 'love',
    color: 'Vivid Green',
    imageUrl: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=400&h=300&fit=crop',
    price: 11499.00,
    currency: 'INR',
    stock: 6,
    buyLink: 'https://www.amazon.in/s?k=emerald+gemstone',
    benefits: 'love|relationships|healing|prosperity|wealth|luck|emotional healing|clarity',
    inStock: true,
  },
  {
    id: 20,
    name: 'Sodalite',
    description: 'A stone of logic, rationality, and efficiency. Sodalite deepens intuition and analytical ability while bringing inner peace.',
    zodiacSigns: JSON.stringify(['Sagittarius', 'Virgo', 'Aquarius']),
    birthMonths: JSON.stringify([9, 10, 12]),
    category: 'clarity',
    color: 'Indigo Blue',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
    price: 1699.00,
    currency: 'INR',
    stock: 19,
    buyLink: 'https://www.amazon.in/s?k=sodalite+crystal',
    benefits: 'clarity|focus|peace|mindfulness|spirituality|wisdom|truth|healing',
    inStock: true,
  },
  {
    id: 21,
    name: 'Selenite',
    description: 'A stone of mental clarity and calm. Selenite cleanses the aura, charges other crystals, and creates a safe space for meditation.',
    zodiacSigns: JSON.stringify(['Cancer', 'Gemini', 'Taurus']),
    birthMonths: JSON.stringify([2, 4, 6]),
    category: 'healing',
    color: 'Translucent White',
    imageUrl: 'https://images.unsplash.com/photo-1494122353872-70a08d729dc3?w=400&h=300&fit=crop',
    price: 1199.00,
    currency: 'INR',
    stock: 24,
    buyLink: 'https://www.amazon.in/s?k=selenite+crystal+wand',
    benefits: 'healing|health|peace|clarity|balance|spirituality|mindfulness|protection',
    inStock: true,
  },
  {
    id: 22,
    name: 'Bloodstone',
    description: 'An excellent blood cleanser and powerful healing stone. Bloodstone heightens intuition and increases creativity and courage.',
    zodiacSigns: JSON.stringify(['Aries', 'Scorpio', 'Pisces']),
    birthMonths: JSON.stringify([3, 10, 12]),
    category: 'health',
    color: 'Dark Green with Red Spots',
    imageUrl: 'https://images.unsplash.com/photo-1503455637927-0be51ce4f3d5?w=400&h=300&fit=crop',
    price: 1399.00,
    currency: 'INR',
    stock: 17,
    buyLink: 'https://www.amazon.in/s?k=bloodstone+gemstone',
    benefits: 'health|healing|vitality|energy|courage|grounding|protection|clarity',
    inStock: true,
  },
  {
    id: 23,
    name: 'Malachite',
    description: 'The stone of transformation and success. Malachite absorbs negative energies, breaks unwanted patterns, and manifests material goals.',
    zodiacSigns: JSON.stringify(['Capricorn', 'Scorpio', 'Taurus']),
    birthMonths: JSON.stringify([1, 5, 11]),
    category: 'success',
    color: 'Vibrant Green with Bands',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
    price: 2599.00,
    currency: 'INR',
    stock: 10,
    buyLink: 'https://www.amazon.in/s?k=malachite+gemstone',
    benefits: 'success|wealth|prosperity|ambition|confidence|healing|protection|energy',
    inStock: true,
  },
  {
    id: 24,
    name: 'Fluorite',
    description: 'The genius stone of focus and higher learning. Fluorite cleanses and stabilises the aura and increases concentration and self-confidence.',
    zodiacSigns: JSON.stringify(['Capricorn', 'Pisces', 'Libra']),
    birthMonths: JSON.stringify([1, 10, 12]),
    category: 'clarity',
    color: 'Multi-coloured Purple and Green',
    imageUrl: 'https://images.unsplash.com/photo-1525869128792-a3c91e3da2a0?w=400&h=300&fit=crop',
    price: 1849.00,
    currency: 'INR',
    stock: 21,
    buyLink: 'https://www.amazon.in/s?k=fluorite+crystal',
    benefits: 'clarity|focus|mindfulness|spirituality|healing|health|protection|wisdom',
    inStock: true,
  },
  {
    id: 25,
    name: 'Red Jasper',
    description: 'The stone of endurance and stamina. Red Jasper brings vitality, strength, and courage while connecting one deeply to Earth energy.',
    zodiacSigns: JSON.stringify(['Aries', 'Taurus', 'Scorpio']),
    birthMonths: JSON.stringify([3, 4, 10]),
    category: 'energy',
    color: 'Brick Red',
    imageUrl: 'https://images.unsplash.com/photo-1511593358241-7eea1f3c84e5?w=400&h=300&fit=crop',
    price: 799.00,
    currency: 'INR',
    stock: 32,
    buyLink: 'https://www.amazon.in/s?k=red+jasper+gemstone',
    benefits: 'energy|vitality|grounding|courage|protection|health|endurance|confidence',
    inStock: true,
  },
  {
    id: 26,
    name: 'Peridot',
    description: 'The gem of cleansing and renewal. Peridot releases negative patterns and old vibrations so a new frequency can be found.',
    zodiacSigns: JSON.stringify(['Leo', 'Virgo', 'Libra']),
    birthMonths: JSON.stringify([7, 8, 9]),
    category: 'health',
    color: 'Lime Green',
    imageUrl: 'https://images.unsplash.com/photo-1576020799627-aeac74d58064?w=400&h=300&fit=crop',
    price: 2899.00,
    currency: 'INR',
    stock: 13,
    buyLink: 'https://www.amazon.in/s?k=peridot+gemstone',
    benefits: 'health|healing|clarity|prosperity|love|peace|energy|balance',
    inStock: true,
  },
  {
    id: 27,
    name: 'Sunstone',
    description: 'A joyful and light-inspiring stone. Sunstone instils joie de vivre, good nature, and heightens intuition while allowing the real self to shine.',
    zodiacSigns: JSON.stringify(['Leo', 'Libra', 'Aquarius']),
    birthMonths: JSON.stringify([7, 9, 10]),
    category: 'success',
    color: 'Glittery Orange-Gold',
    imageUrl: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=400&h=300&fit=crop',
    price: 2199.00,
    currency: 'INR',
    stock: 15,
    buyLink: 'https://www.amazon.in/s?k=sunstone+crystal',
    benefits: 'success|energy|vitality|confidence|joy|optimism|wealth|ambition',
    inStock: true,
  },
  {
    id: 28,
    name: 'Howlite',
    description: 'A calming stone that encourages patience and reduces anger. Howlite facilitates awareness and encourages emotional expression.',
    zodiacSigns: JSON.stringify(['Gemini', 'Scorpio', 'Virgo']),
    birthMonths: JSON.stringify([2, 8, 11]),
    category: 'healing',
    color: 'White with Grey Veins',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    price: 699.00,
    currency: 'INR',
    stock: 40,
    buyLink: 'https://www.amazon.in/s?k=howlite+crystal',
    benefits: 'healing|health|peace|clarity|mindfulness|balance|emotional healing|comfort',
    inStock: true,
  },
  {
    id: 29,
    name: 'Amazonite',
    description: 'The stone of hope and courage. Amazonite calms the brain and nervous system, filters stress and trauma, and enhances loving communication.',
    zodiacSigns: JSON.stringify(['Virgo', 'Aries', 'Aquarius']),
    birthMonths: JSON.stringify([3, 8, 10]),
    category: 'love',
    color: 'Turquoise Green',
    imageUrl: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?w=400&h=300&fit=crop',
    price: 1599.00,
    currency: 'INR',
    stock: 18,
    buyLink: 'https://www.amazon.in/s?k=amazonite+crystal',
    benefits: 'love|healing|peace|clarity|relationships|emotional healing|hope|courage',
    inStock: true,
  },
  {
    id: 30,
    name: 'Iolite',
    description: 'The stone of vision and inner journeying. Iolite strengthens intuition, clears the mind, and supports spiritual exploration and meditation.',
    zodiacSigns: JSON.stringify(['Sagittarius', 'Libra', 'Gemini']),
    birthMonths: JSON.stringify([9, 11, 12]),
    category: 'clarity',
    color: 'Violet Blue',
    imageUrl: 'https://images.unsplash.com/photo-1515387573930-33afba58f2df?w=400&h=300&fit=crop',
    price: 3799.00,
    currency: 'INR',
    stock: 8,
    buyLink: 'https://www.amazon.in/s?k=iolite+gemstone',
    benefits: 'clarity|spirituality|focus|mindfulness|wisdom|peace|healing|truth',
    inStock: true,
  },
];

const runSeeders = async () => {
  try {
    const sequelize = getSequelize();
    const queryInterface = sequelize.getQueryInterface();
    const now = new Date();

    console.log('🌱 Starting seeders (idempotent mode)...\n');

    // ── Users ────────────────────────────────────────────────────────────
    console.log('Seeding users...');
    try {
      await queryInterface.bulkInsert('users', [
        {
          id: 1,
          name: 'Aisha Khan',
          email: 'aisha@example.com',
          password: '$2a$10$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
          role: 'user',
          zodiacSign: 'Libra',
          birthMonth: 10,
          preference: 'love',
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 2,
          name: 'Noah Patel',
          email: 'noah@example.com',
          password: '$2a$10$bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
          role: 'admin',
          zodiacSign: 'Aquarius',
          birthMonth: 1,
          preference: 'clarity',
          createdAt: now,
          updatedAt: now,
        },
      ]);
      console.log('✅ Users seeded (2 records).');
    } catch (err) {
      console.log('⚠️  Users skipped (already exist):', err.message.slice(0, 80));
    }

    // ── Gemstones ────────────────────────────────────────────────────────
    console.log('\nSeeding gemstones...');
    let insertedCount = 0;
    for (const g of GEMSTONES) {
      try {
        await queryInterface.bulkInsert('gemstones', [{ ...g, createdAt: now, updatedAt: now }]);
        insertedCount++;
      } catch {
        // Already exists — skip silently
      }
    }
    console.log(`✅ Gemstones seeded: ${insertedCount} new / ${GEMSTONES.length - insertedCount} already existed.`);

    // ── Recommendations ──────────────────────────────────────────────────
    console.log('\nSeeding sample recommendations...');
    try {
      await queryInterface.bulkInsert('recommendations', [
        {
          id: 1,
          userId: 1,
          zodiacSign: 'Libra',
          birthMonth: 10,
          purpose: 'love',
          gemstones: JSON.stringify([1, 8, 19, 29]),
          createdAt: now,
          updatedAt: now,
        },
        {
          id: 2,
          userId: 2,
          zodiacSign: 'Aquarius',
          birthMonth: 1,
          purpose: 'clarity',
          gemstones: JSON.stringify([7, 15, 20, 24]),
          createdAt: now,
          updatedAt: now,
        },
      ]);
      console.log('✅ Sample recommendations seeded (2 records).');
    } catch (err) {
      console.log('⚠️  Recommendations skipped (already exist):', err.message.slice(0, 80));
    }

    console.log('\n🎉 Seeding complete!\n');
    await sequelize.close();
  } catch (error) {
    console.error('❌ Seeder failed:', error.message);
    process.exit(1);
  }
};

runSeeders();
